---
- yum:
    name: "{{package_name}}"
    state: latest
- template:
    src:  index.html.j2
    dest: /var/www/html/index.html
  notify: udaipur
- service:
    name: "{{service_name}}"
    state: started
